version: '3.3'
services:
  cue-search-backend:
    build:
      context: api
      dockerfile: Dockerfile
    env-file:
      - .env
    volumes:
      - sqliteDB:/code/db:rw
      - djangoStaticFiles:/home/staticfiles:rw
      
  cue-search-frontend:
    build:
      context: ui
      dockerfile: Dockerfile
    env_file:
      - .env
    depends_on:
      - cue-search-backend
    command:
      bash -c "./etc/nginx/conf.d/nginx-entrypoint.sh && nginx -g 'daemon off;'"
    ports:
      - "3000:3000"
    links:
      - "cue-search-backend"
      - "cue-search-redis"
    volumes:
      - djangoStaticFiles:/home/staticfiles:rw
      
  cue-search-redis:
    image: redis

volumes:
  sqliteDB:
  djangoStaticFiles:


    