version: '3.3'
services:
  cue-search-nginx:
    image: nginx:1.17
    volumes:
      - ./ui/nginx-dev.conf.template:/etc/nginx/conf.d/nginx-dev.conf.template
      - ./ui/nginx-entrypoint.sh:/etc/nginx/conf.d/nginx-entrypoint.sh
    command:
      bash -c "./etc/nginx/conf.d/nginx-entrypoint.sh && nginx -g 'daemon off;'"
    env_file:
      - .env.dev
    network_mode: "host"

  cue-search-backend:
    build:
      context: api
      dockerfile: Dockerfile
    volumes:
      - ./api:/code:rw
    command:
      bash -c "chmod +x /code/start_server_new.sh && /code/start_server_new.sh"
    env_file:
      - .env.dev
    network_mode: "host"
    stdin_open: true
    tty: true
    deploy:
      resources:
        limits:
          memory: 4120M

  cue-search-frontend:
    build:
      context: ui
      dockerfile: Dockerfile.dev
    stdin_open: true
    volumes:
      - ./ui/src:/app/src:rw
    network_mode: "host"
    
  # cue-search-postgresql:
  #   image: postgres:13
  #   environment:
  #     - PGDATA=/pg_data
  #     - POSTGRES_DB=cue_observe
  #     - POSTGRES_USER=postgres
  #     - POSTGRES_PASSWORD=postgres
  #   volumes:
  #     - pgdata:/pg_data
  #   network_mode: "host"

  cue-search-redis:
    image: redis
    network_mode: "host"

  cue-search-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - "discovery.type=single-node"
    network_mode: "host"
    # ports:
    #   - 9200:9200


volumes:
  pgdata:
