version: '3.1'
services:
  cue-search-backend:
    image: cuebook/cue-search-backend:0.3.1
    env_file:
      - .env
    volumes:
      - sqliteDB:/code/db:rw
      - djangoStaticFiles:/home/staticfiles:rw
    depends_on:
      - cue-search-redis

  cue-search-frontend:
    image: cuebook/cue-search-frontend:0.3.1
    env_file:
      - .env
    depends_on:
      - cue-search-backend
    command:
      bash -c "./etc/nginx/conf.d/nginx-entrypoint.sh && nginx -g 'daemon off;'"
    ports:
      - "3000:3000"
    links:
      - "cue-search-backend"
      - "cue-search-redis"
      - "cue-search-es"
    volumes:
      - djangoStaticFiles:/home/staticfiles:ro
      
  cue-search-redis:
    image: redis

  cue-search-es:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.2
    environment:
      - "discovery.type=single-node"

volumes:
  sqliteDB:
  djangoStaticFiles:


    