# Generated by Django 3.2.5 on 2022-01-12 19:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("dataset", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="GlobalDimension",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=500, unique=True)),
                ("published", models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name="GlobalDimensionValues",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dimension", models.CharField(max_length=500)),
                (
                    "dataset",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="dataset.dataset",
                    ),
                ),
                (
                    "globalDimension",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="cueSearch.globaldimension",
                    ),
                ),
            ],
        ),
    ]
