# Generated by Django 3.2.5 on 2022-01-13 06:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cueSearch', '0002_searchcardtemplate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globaldimension',
            name='published',
            field=models.BooleanField(default=True),
        ),
    ]
