# Generated by Django 3.2.5 on 2022-01-21 00:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cueSearch', '0002_searchcardtemplate'),
    ]

    operations = [
        migrations.AddField(
            model_name='searchcardtemplate',
            name='renderType',
            field=models.CharField(default='table', max_length=200),
        ),
    ]
