# Generated by Django 3.2.5 on 2022-02-17 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cueSearch', '0003_searchcardtemplate_rendertype'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='searchcardtemplate',
            name='supportedVariables',
        ),
        migrations.AddField(
            model_name='searchcardtemplate',
            name='published',
            field=models.BooleanField(default=False),
        ),
    ]
