# Generated by Django 3.2.5 on 2022-02-18 08:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("dataset", "0001_initial"),
        ("cueSearch", "0004_auto_20220217_0217"),
    ]

    operations = [
        migrations.AddField(
            model_name="searchcardtemplate",
            name="connectionType",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="dataset.connectiontype",
            ),
        ),
    ]
