# Generated by Django 3.2.5 on 2022-02-24 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataset', '0001_initial'),
        ('cueSearch', '0006_auto_20220224_0933'),
    ]

    operations = [
        migrations.AlterField(
            model_name='searchcardtemplate',
            name='connectionType',
            field=models.ManyToManyField(blank=True, to='dataset.ConnectionType'),
        ),
    ]
